### ISSUE TITLE
Incorrect location 

### ISSUE THREAD

**Issue by adadoukis** [DarkMooNight/Rain#106]
Instead of showing the city, it shows the country.

**Comment by Leonavichus** [comment]
What are you looking for? And this question is more likely not to me, but to the service that is used in the application to search for cities.

**Comment by adadoukis** [comment]
I am currently in Nottingham, UK and the application only shows England

**Comment by Leonavichus** [comment]
![Screenshot_2023-10-05-08-22-53-35_978e420477404017796905b3c9af0ff9.jpg](https://github.com/DarkMooNight/Rain/assets/70684753/d01e5897-4cca-4bf9-a4fb-003bf9f54c6a)

Is that what you're looking for?

**Comment by Leonavichus** [comment]
![Screenshot_2023-10-05-08-22-53-35_978e420477404017796905b3c9af0ff9.jpg](https://github.com/DarkMooNight/Rain/assets/70684753/7b515a83-4860-487a-ab1b-f6019e0724b5)

Isn't that what you're looking for?

**Comment by Leonavichus** [comment]
That seems about right. If not, please explain, because I don't quite understand.

![Снимок экрана от 2023-10-05 08-37-14](https://github.com/DarkMooNight/Rain/assets/70684753/9061aea1-f36d-473c-826e-f322eb6f7e43)

**Comment by adadoukis** [comment]
Yes, thank you. But shouldn't the location be recognised automatically?
Aristeidis

**Comment by Leonavichus** [comment]
In the settings, you can enable automatic location search. Does it give out something else?

**Comment by adadoukis** [comment]
It tells me "England" and not the city

**Comment by Leonavichus** [comment]
Can you try this [version] (https://github.com/DarkMooNight/Rain/releases/tag/v.3.5-beta)?

**Comment by adadoukis** [comment]
Thank you for the link.  Same as before.  Not to worry as I am not sure if
I will be using the application to be honest.  I am not a big fun of the
icons at this stage.
