### ISSUE TITLE
Freeze issue

### ISSUE THREAD

**Issue by IM71** [DarkMooNight/Rain#108]
Hi

After update to v.1.2.5, the app freezes.
Please help fix it.

Thanks.

**Comment by Leonavichus** [comment]
Can you tell me what kind of phone and android you have?

**Comment by IM71** [comment]
> Can you tell me what kind of phone and android you have?

S22U (Android 13)

**Comment by Leonavichus** [comment]
Can you try reinstalling the app?

**Comment by IM71** [comment]
> Can you try reinstalling the app?

Reinstalled and problem solved 
Thank you.
