### ISSUE TITLE
Bug: Cant add city

### ISSUE THREAD

**Issue by pabloscloud** [DarkMooNight/Rain#11]
When clicking the save icon in the model/popup nothing happens.

**Comment by Leonavichus** [comment]
Are the data being filled in in the forms below?

**Comment by pabloscloud** [comment]
Except long and lat, yes. It seems like the cursor had been in there but didn't type or sth

**Comment by pabloscloud** [comment]
![fff11097-2fe4-4349-af82-cb221fa41740](https://user-images.githubusercontent.com/93644977/228457736-e969c77c-f7f2-41c2-8252-21a38c1ba797.png)

This is what it looks like after selecting the city. It focused the lat itself

**Comment by Leonavichus** [comment]
Did you click on the city when you selected it in the search? Just the search field should be cleared when selected.![Screenshot_2023-03-29-10-38-07-96_978e420477404017796905b3c9af0ff9.jpg](https://user-images.githubusercontent.com/70684753/228461117-9e88c2f6-c648-4a2a-bd29-ff1f1ee24725.jpg)

**Comment by Leonavichus** [comment]
I'll try to do something, maybe I can fix it.

**Comment by pabloscloud** [comment]
[Uploading screen-20230329-103732.mp4.zip…]()
Github didn't let me upload the video so I compressed it

**Comment by Leonavichus** [comment]
Your compressed video file doesn't want to open with me.

**Comment by Leonavichus** [comment]
Can you see if adding a city works now?

**Comment by pabloscloud** [comment]
![Screenshot_20230329-141409](https://user-images.githubusercontent.com/93644977/228532272-6b2d6f37-30b9-4cf2-a1f4-6175915bf515.png)

**Comment by Leonavichus** [comment]
Will you be able to send me a video in a telegram so that I can roughly understand how it works for you?

**Comment by pabloscloud** [comment]
I don't have telegram but I sent a video before

**Comment by pabloscloud** [comment]
[screen-20230329-103732.mp4.zip](https://github.com/DarkMooNight/Rain/files/11100908/screen-20230329-103732.mp4.zip)

**Comment by Leonavichus** [comment]
[app-arm64-v8a-release.zip](https://github.com/DarkMooNight/Rain/files/11104265/app-arm64-v8a-release.zip)

Can you try this version?

**Comment by pabloscloud** [comment]
[screen-20230329-205516.mp4.zip](https://github.com/DarkMooNight/Rain/files/11104523/screen-20230329-205516.mp4.zip)
Sure, here is the result

**Comment by Leonavichus** [comment]
I don't understand why the fields aren't filled in and I can't reproduce this bug.😞
Do you have a regular Android or its fork?

**Comment by pabloscloud** [comment]
Good catch!

I am using a pixel 4a 5g with calyxOS

**Comment by pabloscloud** [comment]
Android 13
CalyxOS 4.7.5

**Comment by pabloscloud** [comment]
I could send you some logs if that could help

**Comment by Leonavichus** [comment]
Perhaps this is the problem, then tomorrow, starting from this, I will try to fix this bug.

**Comment by Leonavichus** [comment]
> I could send you some logs if that could help

I will be grateful.

**Comment by pabloscloud** [comment]
Thanks for all the time you took already to fix this

**Comment by pabloscloud** [comment]
[bugreport-bramble-TQ2A.230305.008.C1-2023-03-29-21-15-58.zip](https://github.com/DarkMooNight/Rain/files/11104682/bugreport-bramble-TQ2A.230305.008.C1-2023-03-29-21-15-58.zip)

**Comment by Leonavichus** [comment]
Thanks.

**Comment by Leonavichus** [comment]
[app-arm64-v8a-release.zip](https://github.com/DarkMooNight/Rain/files/11105120/app-arm64-v8a-release.zip)

Try this version, it should work.

**Comment by pabloscloud** [comment]
[screen-20230330-061150.mp4.zip](https://github.com/DarkMooNight/Rain/files/11107669/screen-20230330-061150.mp4.zip)

Just like on the home screen before, I can't select it at all now.

**Comment by pabloscloud** [comment]
[bugreport-bramble-TQ2A.230305.008.C1-2023-03-30-06-15-26.zip](https://github.com/DarkMooNight/Rain/files/11107683/bugreport-bramble-TQ2A.230305.008.C1-2023-03-30-06-15-26.zip)

**Comment by Leonavichus** [comment]
How difficult.

**Comment by pabloscloud** [comment]
I would love to give you some information or advice idk but I never had this or a similar issue with other apps (yet)

**Comment by Leonavichus** [comment]
The problem is that I can't even reproduce this error on any phone, I even installed an emulator with CalyxOS, but everything works there too.

**Comment by Leonavichus** [comment]
Try downloading app-release.apk in the new version, maybe it will work.

**Comment by pabloscloud** [comment]
Mhh, still doesn't work. I think you can shift your focus on other issues. Maybe someone else knows exactly what this is caused by and fixes it quickly in the future. I'll use the GPS location instead til then. Should it ever work I'll notice it and leave a comment

**Comment by Asherathe** [comment]
I have the same issue on Android 13/ Galaxy Flip 3. Manually filling in longitude and latitude allows a city to be added, but selecting a city by name will not auto-populate the info.

**Comment by pabloscloud** [comment]
@Asherathe 
> Android 13
Is it regular android or also a fork?

**Comment by Asherathe** [comment]
> > Android 13
> 
> Is it regular android or also a fork?

In my case, it's regular Android.

**Comment by SebiTalent04** [comment]
I have the same issue, when I type in the city name, a list with matching names appears but I can't select any of them.

Pixel 6a, Android 13/GrapheneOS

**Comment by Leonavichus** [comment]
What a pain, why so.

**Comment by Leonavichus** [comment]
I'll try to replace the autofill widget, maybe it will help.

**Comment by Leonavichus** [comment]
[app-arm64-v8a-release.zip](https://github.com/DarkMooNight/Rain/files/11129247/app-arm64-v8a-release.zip)
@pabloscloud, @Asherathe, @SebiTalent04 , can you see if adding a city works now?

**Comment by pabloscloud** [comment]
@Leonavichus if you provide us with a new apk

**Comment by Leonavichus** [comment]
https://github.com/DarkMooNight/Rain/releases/tag/v.2.2-pre

**Comment by SebiTalent04** [comment]
It's weird, for some cities works but for others doesn't work.

https://anonfiles.com/4bd4r7i3z7/screen_20230401_145626_mp4

**Comment by SebiTalent04** [comment]
Ohh, I forgot about that. It autocompletes fine now, as it should

**Comment by Leonavichus** [comment]
It's good.

**Comment by Leonavichus** [comment]
@Asherathe, @pabloscloud, does it work for you?

**Comment by Leonavichus** [comment]
I posted a new version, please see if everything works.

**Comment by SebiTalent04** [comment]
Yay, it works in the first screen too. Thanks!

**Comment by SebiTalent04** [comment]
Yay, it works in the first screen too. Thanks!

**Comment by Asherathe** [comment]
> can you see if adding a city works now?

It does work for me now.

**Comment by pabloscloud** [comment]
The bus seems to be resolved for everyone now. Thanks for the contributions from others and thanks to the developer for the quick fix!
