### ISSUE TITLE
Add open source licenses page

### ISSUE THREAD

**Issue by shatanikmahanty** [DarkMooNight/Rain#115]
Hi, it would be great if we could show an open source licenses option in settings. Making it is really simple, flutter has an inbuilt LicensePage that displays all available licenses.

If you agree, I can land a PR for the same

**Comment by Leonavichus** [comment]
I would be very grateful

**Comment by shatanikmahanty** [comment]
I will work on this soon and raise a PR!

**Comment by Leonavichus** [comment]
Thank you so much for all the work done! ❤️‍🔥

**Comment by shatanikmahanty** [comment]
I have also added translations through Github Copilot auto code generation. Will push that.
