### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Fabeuss** [DarkMooNight/Rain#12]
Very nice application, I would love to see it translated into my language (French).
Could you set up a translation system like Weblate or something else, I would be happy to participate...

**Comment by Leonavichus** [comment]
I could try, but you can also do pull requests with the modified translation file.

**Comment by Fabeuss** [comment]
Nice, I will work on it. Thanks

**Comment by Leonavichus** [comment]
In the next update that will be today-tomorrow there will be your translation.

**Comment by Fabeuss** [comment]
Thanks a lot :+1:
