### ISSUE TITLE
Dynamic home screen icon based on weather

### ISSUE THREAD

**Issue by shatanikmahanty** [darkmoonight/Rain#122]
Proposal:

To change app icon based on current weather status. Default will be the rain icon we have currently.

Can be achieved with this package: https://pub.dev/packages/dynamic_icon_flutter

Was thinking of something like this:
![image](https://github.com/DarkMooNight/Rain/assets/67138059/1819f18a-7545-466b-9059-71d78b0e204e)

I Will raise a PR if this will be relevant to users. Let me know your thoughts

Edit: App icon now changes dynamically. 

Future changes in consideration:

- [ ] Figure out a way to change app icon on every weather update cycle rather than only on location change or app open
- [ ]  Optimise change icon call by checking if the current icon is same as the one we are trying to change to
- [ ]  Let users decide if they want this feature through a switch in settings. By default I will keep this false as android restarts app on changing icon
- [ ]  Let users decide if the icon changes on closing app or instantly

**Comment by Leonavichus** [comment]
That would be great.
