### ISSUE TITLE
Weird notifications.Which is not good for User Experience (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [darkmoonight/Rain#128]
![Screenshot_2023-10-22](https://github.com/darkmoonight/Rain/assets/49509445/f332ee33-75d0-4af7-bba0-4e50a48230f2)

I think these notifications will confuse users and I don't think its helping users in any way so they should be removed Or make it user-friendly...

**Comment by Leonavichus** [comment]
Such a video is only in the debut version, it should not be in the release.

**Comment by Leonavichus** [comment]
This is visible only in the debug version, this should not be in the release.

**Comment by NomanBaigA** [comment]
> This is visible only in the debug version, this should not be in the release.


Okay cool, Thanks
