### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by senolfndk** [DarkMooNight/Rain#13]
Can you add Turkish language in the application?

**Comment by Leonavichus** [comment]
I can, but I'll have to use a translator since I don't know Turkish. If it's not difficult for you, you can perform extraction requests using the modified translation file.

**Comment by senolfndk** [comment]
I'm not an expert on this

**Comment by Leonavichus** [comment]
Then do you mind if it's machine translation?

**Comment by Leonavichus** [comment]
In the new version, the Turkish language has been added.

**Comment by senolfndk** [comment]
![Screenshot_20230330-141622.jpg](https://user-images.githubusercontent.com/52818836/228819679-a476224e-2460-477f-bd94-a0670ed13460.jpg)

Degree not visible

**Comment by Leonavichus** [comment]
Strange, I have everything displayed

**Comment by Leonavichus** [comment]
Try refreshing the page, it may not load

**Comment by Leonavichus** [comment]
Loaded or not?

**Comment by senolfndk** [comment]
unfortunately same problem

**Comment by Leonavichus** [comment]
Before I added Turkish, did you use the app?

**Comment by senolfndk** [comment]
yes

**Comment by senolfndk** [comment]
yes the previous version had the same problem

**Comment by senolfndk** [comment]
ok fixed

**Comment by senolfndk** [comment]
Yes
