### ISSUE TITLE
{Bug Report} It's not able to find  location in Android 6.0 Device, The Debug version is working fine problem exists with release version only. (Video clip provided)

### ISSUE THREAD

**Issue by NomanBaigA** [darkmoonight/Rain#132]
Important points :
- App is working if I am downloading it from Google Play in my Android 6.0 device.
- Same release apk (The one created by me) is working fine on Android 9 and 11 device.

Screen Record -

https://github.com/darkmoonight/Rain/assets/49509445/0a7941e8-fe3f-4bb2-a6e4-c2b45c281ce6

**Comment by Leonavichus** [comment]
I don't know what your problems are with the application build. Everything works fine for me both in debug and in release.

**Comment by NomanBaigA** [comment]
Error during city search - 

"I/flutter (29778): DioException [unknown]: null
I/flutter (29778): Error: HandshakeException: Handshake error in client (OS Error: 
I/flutter (29778): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
E/flutter (29778): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DioException [unknown]: null
E/flutter (29778): Error: HandshakeException: Handshake error in client (OS Error: 
E/flutter (29778): 	CERTIFICATE_VERIFY_FAILED: certificate has expired(handshake.cc:393))
E/flutter (29778): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507:7)
E/flutter (29778): #1      _RootZone.runUnary (dart:async/zone.dart:1661:54)
E/flutter (29778): #2      _FutureListener.handleError (dart:async/future_impl.dart:174:22)
E/flutter (29778): #3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
E/flutter (29778): #4      Future._propagateToListeners (dart:async/future_impl.dart:873:13)
E/flutter (29778): #5      Future._completeError (dart:async/future_impl.dart:649:5)
E/flutter (29778): #6      _SyncCompleter._completeError (dart:async/future_impl.dart:60:12)
E/flutter (29778): #7      _Completer.completeError (dart:async/future_impl.dart:26:5)
E/flutter (29778): #8      Future.any.onError (dart:async/future.dart:620:45)
E/flutter (29778): #9      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (29778): #10     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
E/flutter (29778): #11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
E/flutter (29778): #12     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
E/flutter (29778): #13     Future._completeError (dart:async/future_impl.dart:649:5)
E/flutter (29778): #14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:739:7)
E/flutter (29778): #15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (29778): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)"

**Comment by NomanBaigA** [comment]
This error is with Android 6 only...
Everything works fine in Android 9 and 11...
