### ISSUE TITLE
Weather is still updating after adding cities. It was working with one city earlier

### ISSUE THREAD

**Issue by penguinkb** [DarkMooNight/Rain#15]

**Comment by Leonavichus** [comment]
I don't quite understand what you're talking about

**Comment by penguinkb** [comment]
![Screenshot_2023-03-30-16-43-34-003_com.yoshi.rain.jpg](https://user-images.githubusercontent.com/13046768/228855769-9ba8883e-7219-48ba-8ee2-56cea9fc252a.jpg)

Check this screenshot

**Comment by penguinkb** [comment]
Cleared the cache and data. That helped

**Comment by Leonavichus** [comment]
Understood, can I close this problem?

**Comment by penguinkb** [comment]
Had that issue with 1.0.9

Now there is a new version
Will download and test it

**Comment by Leonavichus** [comment]
Now I want to fix all the bugs, then I'll add the widget to the home screen. And then it will be seen.

**Comment by penguinkb** [comment]
Yes. Thanks. Looks nice and it's getting better and better.

In the new release 1.1.5 saw the sunrise and sunset. Below it you can add moonrise and moonset.
For the future release you can also add about moon phases.

Also, about eclipses and astronomical events if you think of it will make sense.

Like all-in-one app. So far, I haven't seen this feature in any weather app

Thanks again.

________________________________
