### ISSUE TITLE
Point Degree

### ISSUE THREAD

**Issue by DeadSecTr** [darkmoonight/Rain#158]
Please remove the point degree (1.2°,0.8°)

![Screenshot_20240127-203007.png](https://github.com/darkmoonight/Rain/assets/90558189/820f6b2a-7ec8-40ec-8a8e-a24c16d626fc)

**Comment by Leonavichus** [comment]
Well

**Comment by DeadSecTr** [comment]
Or maybe a toggle?

**Comment by Leonavichus** [comment]
Yes, that's what I was going to do.
