### ISSUE TITLE
Understanding temperature values for upcoming days /Changing the values to min/max

### ISSUE THREAD

**Issue by cu1tur4l** [darkmoonight/Rain#160]
So sorry for deleting the issue template, but it will (I think) not be helpful here.
Also sorry if its a duplicate of #99, if so I also would like to understand why it was rejected.

tl;dr 
I would like to be able to change black/gray values to display min/max temperature for upcoming days. If not possible, would like to know what they are now and why such idea was rejected.

not tl;dr
<details>I can't understand temperature values for upcoming days (black / gray values). In all apps I've come across the numbers along the upcoming days are min/max temperatures, but on Rain they aren't or they are broken - which is hard to believe since it would be a very major bug, that anyone would notice before me, unless I'm the only one having this problem, which is also very unlikely. If I click on a day, the values differ from min/max values when you click on certain day. I would love to have an option to change it for min/max values. Since I don't know what they are (which is of course my fault) I cannot just know the temperature at a glance, instead I have to click on every single day to learn it from the data provided there. Such a first world problem, I know, I feel stupid "complaining" about it but yeah. </details>

Of course I think this is intentional, so screenshot is pointless, but since I'm describing an issue, I think involving a screenshot that explains it is necessary.
![Untitled](https://github.com/darkmoonight/Rain/assets/102048095/2a12a466-becc-43f3-9191-22df1d7b2732)

Either way I plan on using the app because it is very very very beautiful, and beside my 'problem' does everything that is expected from such app, heck, it does even more, and provides it perfectly (visually). Thank you for making it ❤️ ❤️ ❤️

**Comment by Leonavichus** [comment]
In the second screenshot, the underlined values are the maximum/minimum apparent temperature.

**Comment by cu1tur4l** [comment]
Lol, you know why it happen? Because the default language app chose, was my system language, and when I changed it to English I didn't even bother to look at the apparent min/max name... In my language the I could only see "minimum... maximum..." so that's why i thought they are min/max values... So sorry, now I feel even stupider :))) Thank you so much for explaining it <3 That's all
