### ISSUE TITLE
Attribution to the weather data source in the app

### ISSUE THREAD

**Issue by KoolTechTricks** [darkmoonight/Rain#179]
The attribution to Open-Meteo is only in README.md. Neither app stores description, nor in the app itself, has any information about where the weather data comes from. This could potentially cause confusion between different apps. Also, this doesn't comply with [Open-Meteo's terms](https://open-meteo.com/en/terms), as the data is offered under CC-BY 4.0 license, which requires leaving attribution.

Example implementations:
![Attribution at the bottom of main screen](https://github.com/darkmoonight/Rain/assets/142810154/e259d59e-4189-4bb2-91ad-82dcf5b6537d)
![Attribution in location's description](https://github.com/darkmoonight/Rain/assets/142810154/8a70073e-4db4-4230-9208-2aa8df1af1fe)

**Comment by Leonavichus** [comment]
Thanks for telling me. I will add it in the next version.
