### ISSUE TITLE
Start time / end time AM PM bug

### ISSUE THREAD

**Issue by blasf69** [darkmoonight/Rain#183]
Under Settings/Functions and after entering a 'Start time' or 'End time' then back in the settings function menu the time always show up as being AM even if PM is entered. EXCEPT for times 12:00 - 12:59 which the opposite occurs and PM only shows.

**To Reproduce**
1. Settings
2. Functions
3. Scroll down to 'Start time' or 'End time'
4. Select a time in AM or PM

**Expected behavior**
For example: entering a 'Start time' of 11:00 PM afterwords 11:00 AM will show in the menu.

**Screenshots**
![Screenshot_20240619-152944](https://github.com/darkmoonight/Rain/assets/5494718/4ccd782c-c9d8-4a58-8d79-aee22ffacd71)
![Screenshot_20240619-152954](https://github.com/darkmoonight/Rain/assets/5494718/abe86454-212d-4863-bf1f-ff188ec62b4c)

**Smartphone (please complete the following information):**
 - Device: Pixel 5a
 - OS: Android 14
 - Browser  Chrome 
 - version 126.0.6478.72

**Additional context**
Shortened version: No matter what time I select for 'Start' or 'End' time it displays time as AM except 12:00 - 12:59 when PM is only displayed.
App version: 1.3.1

**Comment by Leonavichus** [comment]
It's strange, everything works correctly for me. Could you record a video?
