### ISSUE TITLE
Update the app on Playstore

### ISSUE THREAD

**Issue by WarFiN123** [darkmoonight/Rain#187]
**Describe the bug**
The Playstore version is still at 1.3.1

**To Reproduce**
1. Go to the Google Playstore
2. Search for the app
3. Click on 'About this app'
4. See version

**Expected behavior**
Version should be latest which is 1.3.3 as of 14/7/24

**Screenshots**
![Screenshot_20240714_164334.jpg](https://github.com/user-attachments/assets/c13a2f54-21c7-4f8b-99b0-2346b98ce5f5)

![Screenshot_20240714_164345.jpg](https://github.com/user-attachments/assets/9e10a65f-1dcc-4ae4-bf2e-7b1bc0dcb29d)

**Smartphone (please complete the following information):**
 - Device: iQOO Neo 6
 - OS: Android 14
 - Browser Brave/Chrome
 - Version N/A

**Comment by Leonavichus** [comment]
I downloaded the update, it will be coming soon.
