### ISSUE TITLE
Feedback and improvements to the Map tab

### ISSUE THREAD

**Issue by PhilippKosarev** [darkmoonight/Rain#191]
I think the Map tab is great if you have too many cities and dont want to scroll through a list. But here are some improvements (in my opinion) which would be nice to have.

1. Disable map rotation. Rotating the Map doesn't really serve any purpose and can get annoying when you are trying to zoom in or out. If some people like it a toggle might be required.

2. Start more zoomed out. At the default zoom level I can only really see my current city, so I have to zoom out every time which isn't very fun.

3. Add an option to hide the Map tab. Some people, me included, only use the app to check weather of only one city, so having an option to disable or hide it from the nav bar would be useful.

**Describe alternatives you've considered**
As for hiding the Map tab, maybe having an option to swap it with the Cities tab instead could be beneficial. Both tabs mostly have the same purpose, but that would require additional work to add the Cities Tab's functionality to the Map tab.

Thank you for your time.
Also, I'm not familiar with android development, and so cannot be of much use. So I'm sorry if that is too much work to ask for, for free.

**Comment by Leonavichus** [comment]
Hi, thanks for the feedback. I will definitely consider your comments for the next update.

**Comment by Leonavichus** [comment]
Hi, can I close this task?

**Comment by PhilippKosarev** [comment]
Sure, thank you for hearing the feedback :)
