### ISSUE TITLE
Random crashes when opening the app

### ISSUE THREAD

**Issue by zanyshh** [darkmoonight/Rain#192]
**Describe the bug**
app randomly crashes and does not open when trying to open it to reopen the app i had to go to android app settings to clear the cache and storage for the app to work like normal

**To Reproduce**
1. Go to 'just open the app with 2 apps in the background and it would crash and the app would not open'

**Expected behavior**
i expected the app to open normally and not crash

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.2.8

**Smartphone (please complete the following information):**
 - Device: Vivo V40
 - OS: Android 14
 - Browser  Chrome
 - Version 1.2.8

**Comment by Leonavichus** [comment]
It is not possible to reproduce the problem, everything is working stably. Can you record a video?
