### ISSUE TITLE
Sun up and sun down times

### ISSUE THREAD

**Issue by flugeldude** [DarkMooNight/Rain#20]
Please add sun up and sun down times per location

**Comment by Leonavichus** [comment]
I can't do this because the api I use doesn't have this.

**Comment by Leonavichus** [comment]
Found a way to implement it.

**Comment by Leonavichus** [comment]
This has been fixed in the new version.

**Comment by azlux** [comment]
As option ? No ?
I wasnt expecting see sun time here.

**Comment by Leonavichus** [comment]
> Как вариант ? Нет ? Я не ожидал увидеть здесь солнечное время.

I don't quite understand you.

**Comment by azlux** [comment]
Srry, I was suggesting to make this feature as an option (something that can be disabled into the application's parameter). Or maybe at least after the forecasts, for a better forecast application.
