### ISSUE TITLE
High Refresh Rate support

### ISSUE THREAD

**Issue by AISLVE** [DarkMooNight/Rain#21]
For some reason,the app is locked at 60Hz.althpugh it supports 120Hz.BTW the phone model is Nothing Phone 1 and has an unlocked BL

**Comment by Leonavichus** [comment]
It's strange, everything works for me.

**Comment by Leonavichus** [comment]
Can you see if it works for you now?

**Comment by AISLVE** [comment]
Yeah,working fine nkw
