### ISSUE TITLE
No internet connection error

### ISSUE THREAD

**Issue by Alexandru51** [DarkMooNight/Rain#3]
When trying to choose a city, it only shows "No internet connection" and nothing happens.

**Comment by Leonavichus** [comment]
Сan you take a screenshot?

**Comment by Alexandru51** [comment]
https://user-images.githubusercontent.com/94460645/226197282-0cc1b0a0-56d7-46e1-bb79-83624d5acfb0.mp4

**Comment by Leonavichus** [comment]
Hmm, strange, what version of Android do you have?

**Comment by Alexandru51** [comment]
Android 12, and my device is Xiaomi Redmi Note 9

**Comment by Leonavichus** [comment]
I will try to fix this problem by the next update.

**Comment by Leonavichus** [comment]
I can't reproduce your error in any way and I don't understand what it is connected with.😞

**Comment by Asherathe** [comment]
I have a similar problem on Galaxy Z Flip 3 running Android 13. I don't get the "no internet" popup, but everything else is the same. The app appears to be loading, but just loads forever. Firewall shows it contacting lots of dns servers, which seems odd.

**Comment by Leonavichus** [comment]
@Asherathe, @Alexandru51, can you see if the app is working for you now?

**Comment by Alexandru51** [comment]
https://user-images.githubusercontent.com/94460645/227795102-42e41727-3647-4a47-9672-cda117243ba6.mp4

Nope, still the same thing, but allows me to search for cities (i chose Bucharest as an example). So yea, probably something wrong with API or i don't know.

**Comment by Leonavichus** [comment]
Perhaps this is a problem with the Internet connection verification plugin.

**Comment by Alexandru51** [comment]
> Perhaps this is a problem with the Internet connection verification plugin.

Nevermind, it's partially working i guess...
I had to use a vpn to make it work

**Comment by Asherathe** [comment]
The main screen now loads for me, after searching for and selecting my city. 

Adding a city does not work. Even though my city appears in the dropdown list, selecting it does not fill in coordinates.
