### ISSUE TITLE
[FEATURE REQUEST] Manage cities on the cities tab

### ISSUE THREAD

**Issue by fabiandrinksmilk** [DarkMooNight/Rain#43]
Option to reorder cities on the cities tab.

I think it would be useful to be able to change the order without deleting all cards and adding them again. Other options could be added like copying some kind of information or share the weather in some way.

Possible implementations:

- Long press a card to reorder it
- Long press card to show a drop down menu with options to reorder and delete
- Replace the floating action button with a speed dial with options to add, reorder and/or delete cards
- Change the cities screen to only show cards and have a floating action button that links to an edit screen where you can add, delete and reorder cards

**Comment by Leonavichus** [comment]
You can delete the weather card by swiping it with your finger to the left.

**Comment by fabiandrinksmilk** [comment]
> You can delete the weather card by swiping it with your finger to the left.

Thanks, I did not know that yet. I'll edit the issue then.
