### ISSUE TITLE
Вопрос о автоматическом определении города и провайдере.

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#49]
Почему ты не хочешь использовать автоматический поиск города с помощью других провайдеров с открытым кодом или более склонных к конфиденциальности?

Вместо этого ты используешь поиск местоположения от гугла. Есть прекрасные альтернативы (абсолютно Все лучше гугла). Несмотря на небольшую неточность, для определения городов это подходит. Так почему ты не хочешь?

гугл это шпион, по этому очень странный выбор его засовывать в приложение с открытым кодом которое старается быть конфиденциальным.

**Comment by Leonavichus** [comment]
Я конечно попробую поискать или что-нибудь придумать, но ничего не обещаю.

**Comment by Leonavichus** [comment]
Я попробую это реализовать.

**Comment by Leonavichus** [comment]
Что-то по ip он меня находит в Краснодаре, хотя я в Ростове.

**Comment by Leonavichus** [comment]
По ip не вариант, показывает местоположение провайдера, через wi-fi показывает все нормально, а через мобильную сеть нет.

**Comment by Leonavichus** [comment]
Я как раз таки это сейчас и использую

**Comment by Leonavichus** [comment]
Хорошо, я посмотрю.

**Comment by Leonavichus** [comment]
[app-arm64-v8a-release.zip](https://github.com/DarkMooNight/Rain/files/11391004/app-arm64-v8a-release.zip)
Я сделал вроде как сделал, посмотрите будет ли у вас это работать.

**Comment by Myzel394** [comment]
Hey, I saw that @Wjxfi linked one of my issues to this. When my translator is correct, you are trying to degoogle your app. I saw that you already edited your `pubspec.yaml` file - to fully degoogle your app, I would also recommend you to exclude gms from your [`android/build.gradle`](https://github.com/DarkMooNight/Rain/blob/main/android/app/build.gradle) - like I did it here: https://github.com/Myzel394/locus/blob/master/android/app/build.gradle#L94

Note though that some functionality may break, so please first make sure to review everything. I'm currently trying if MicroG could replace some functionality, but I'm not sure yet.

Btw, your app looks gorgeous :D

**Comment by Leonavichus** [comment]
@Myzel394, thank you so much for your help!

**Comment by Myzel394** [comment]
@Leonavichus no problem, I haven't figured out how to properly include MicroG yet :/ if you find a way, please let me know

**Comment by Leonavichus** [comment]
@Myzel394, Sure

**Comment by Leonavichus** [comment]
/home/yoshi/Документы/Flutter/Rain/build/app/outputs/flutter-apk/rain-foss-arm64-v8a-release.zip
@Wjxfi, можете посмотреть все ли у вас работает и gms больше нет?

**Comment by Leonavichus** [comment]
у меня все нормально работает

**Comment by IzzySoft** [comment]
Thanks for the ping, @Wjxfi – anti-features removed (effective with the next sync around 6 pm UTC).

And thanks to the team of contributors for the efforts taken :heart_eyes:
