### ISSUE TITLE
Pop up window to grant permission for the location does not show.

### ISSUE THREAD

**Issue by avocadeys** [DarkMooNight/Rain#50]
when toggling the toggle button for location, nothing pops up to grant permission for location access.

here's a screen record.

https://user-images.githubusercontent.com/121883478/234477849-381be7b3-80a6-4883-8beb-b4cd3430bc0e.mp4

**Comment by Leonavichus** [comment]
It will appear when the main page is updated.

**Comment by avocadeys** [comment]
oh, my bad. i tried to turn it and refresh the main page, and now it shows up! thanks again, @Leonavichus!
