### ISSUE TITLE
Weather detail screens not loading

### ISSUE THREAD

**Issue by larouxn** [DarkMooNight/Rain#51]
After the latest updates (1.1.8 + 1.1.9) both the app's primary screen and saved city weather screens fail to load.

Troubleshooting steps tried:
- Force stopping
- Clearing cache
- Clearing data

Home screen fails to load.

![Screenshot_20230426-182743.png](https://user-images.githubusercontent.com/1557529/234533819-1330775b-768f-48c3-a9be-a2c4b8023560.png)

Saved city weather screen loads fine but clicking any of the cities brings up this grey screen.

![Screenshot_20230426-182934.png](https://user-images.githubusercontent.com/1557529/234533959-2f1f383a-7d53-46a9-aeeb-836da4044b83.png)

![Screenshot_20230426-182853.png](https://user-images.githubusercontent.com/1557529/234533979-2de6f48c-cb6f-4f9b-92aa-a61fd270a4c9.png)

**Comment by Leonavichus** [comment]
Do you use a search engine or by location?
What is your Android version ?
Everything works for me after deleting all the data, have you tried reinstalling the application?

**Comment by larouxn** [comment]
> Do you use a search engine or by location?

If I search for a location on the home screen it works fine. If I try by location, it does not work.

> What is your Android version ?

Android 13, April 5th revision (Pixel)

> Everything works for me after deleting all the data, have you tried reinstalling the application?

Just tried uninstalling and reinstalling. That has fixed the issue. 🙇‍♂️
