### ISSUE TITLE
сейчас перемещение по 10 дням слишком медленное. Новый метод (справа линия)

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#55]
можно сделать как видно ниже
https://user-images.githubusercontent.com/113500363/235224946-04529c03-f854-4b2f-8efc-2f8215e6d422.mp4

если тянуть эту линию оно будет гораздо быстрее идти а не медленно как сейчас

**Comment by Leonavichus** [comment]
Да мне тоже не нравится. Буду думать как это лучше сделать в плане размещения информации, удобства и эффективности.
