### ISSUE TITLE
10 дней функция. Возможность посмотреть полную информацию о дне

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#56]
около любого из 10 дней (у всех) будет ненавязчивая кнопка "посмотреть полную версию дня". Она будет показывать то что пользователь видит на главном экране (в 1 вкладке). Также, там можно будет посмотреть почасовую информацию (и всю остальную). Сейчас 10 дней слишком поверхностны

**Comment by Leonavichus** [comment]
Если показывать по часам то теряется смысл этих 10 дней, так как на главном экране это можно посмотреть проскроллив до нужной даты и нажать на  интересующий вас час. В информации о дне я показываю максимальное/минимальное значения, либо сумму значений за день.

**Comment by Leonavichus** [comment]
Я подумаю над этим.
