### ISSUE TITLE
Auto location is broken in 1.1.9

### ISSUE THREAD

**Issue by venetin** [DarkMooNight/Rain#57]
Hello,

The automatic location recognition is broken in 1.1.9.
The app is even not trying to ask for the location permition.
The github release is asking for permission but still can't locate me. 
Tried clean install with no luck.
Reverted to 1.1.8 and everything is working.
I am using the f-droid build.

**Comment by Leonavichus** [comment]
I understand you, I will fix this in the new version.

**Comment by Leonavichus** [comment]
[app-arm64-v8a-release.zip](https://github.com/DarkMooNight/Rain/files/11391009/app-arm64-v8a-release.zip)
Can you see if the location will work for you?

**Comment by venetin** [comment]
Hi,
I can't test right now because I am in the city which can't be found even on 1.1.8 version. Actually some other weather apps can't find this location. 
But I can see that the location icon appear in the status bar. 
I will be back home on Friday or on Saturday.

**Comment by venetin** [comment]
Hello,
I managed to make some tests. It seems that the location is fixed in 1.1.10. But it seems that it is not the perfect solution. Bot on 1.1.8 and 1.1.10 the location need a lot of time to be determined. Sometimes it takes 3-5 minutes. I am testing this on Huawei phone with no GMS. I also tested all the versions on a GMS phone and it seems that 1.1.8 is the best in terms of location.
