### ISSUE TITLE
При попытке обновления главного экрана (1 вкладка) пишет нет интернета, хотя он есть.

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#58]
При попытке обновления главного экрана (1 вкладка) пишет нет интернета, хотя он есть.

**Comment by Leonavichus** [comment]
Странно, у меня все нормально работает.

**Comment by Leonavichus** [comment]
Когда у вас это началось?

**Comment by Leonavichus** [comment]
Я не знаю в чем проблема, у меня все работает стабильно. Попробуйте переустановить приложение.

**Comment by Leonavichus** [comment]
В новой версии у вас присутствует эта ошибка?
