### ISSUE TITLE
Temperatures still shown in Celsius when Fahrenheit is selected in settings. 

### ISSUE THREAD

**Issue by basnappl** [DarkMooNight/Rain#61]
Hi,

Gave your app a try. I changed the "Degrees" setting to Fahrenheit and restarted the app. The symbol for the units did, indeed, change to "F" from "C", but the numerical values did not change.

Thanks!

**Comment by Leonavichus** [comment]
Hi, try updating the data. On the main screen, swipe down. This is due to the fact that the data is entered in db and for this it is necessary to update.

**Comment by basnappl** [comment]
That fixed it, thanks.

------- Original Message -------

**Comment by paulshryock** [comment]
I'm on version 1.3.13, and the temperature never changes from Celcius to Fahrenheit. The C changes to F, but the degrees stays the same. Swiping down reloads and does nothing. The degrees don't change.

**Comment by paulshryock** [comment]
I was able to get the degrees to update by searching for my city and starting over.

**Comment by Leonavichus** [comment]
@paulshryock, Fixed it
