### ISSUE TITLE
убрать сегодняшний день в десяти днях (не нужен, он и так на главной странице)

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#66]
![d007a3e6-21cc-4944-92e2-fc94ba806ac1.jpg](https://github.com/DarkMooNight/Rain/assets/113500363/e176afc7-8060-4e2e-89f6-8c6524453cd3)

**Comment by Leonavichus** [comment]
Там показываются другие данные, так что не планирую.
