### ISSUE TITLE
убрать кнопку "Прогноз погоды на 10 дней" и оставить дни снизу главного экрана.

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#67]
я хочу чтобы добавили еще три дня снизу и убрали кнопку "Прогноз погоды на 10 дней" так как внутри этой кнопки абсолютно такая же информация

![4bfb6848-d7ab-4331-91d7-87acf80abf47.jpg](https://github.com/DarkMooNight/Rain/assets/113500363/a441977b-ae65-4375-a1dc-ba22f6bc59ae)

посмотри. Сверху такая же информация как и снизу. Нет смысла кнопки "Прогноз погоды на 10 дней". Лучше добавить три дня (которых нет (8,9,10)) в место со скриншота сверху и тогда будет то же самое как и в кнопке "Прогноз погоды на 10 дней" без нажатия на кнопку "Прогноз погоды на 10 дней".

![271badb8-9bc2-40c0-8a31-7e87fc2a72b3.jpg](https://github.com/DarkMooNight/Rain/assets/113500363/942e42d7-ef49-4ef0-a26d-8d56177e7d51)

**Comment by Leonavichus** [comment]
Большинство людей попросту не догадается нажать на день, чтобы открылось подробное описание. Если я сделаю так люди попросту не будут знать об этом.

**Comment by Leonavichus** [comment]
И давайте общаться без всяких фамильярностей и "я хочу".
