### ISSUE TITLE
Widget 

### ISSUE THREAD

**Issue by Roterfux** [DarkMooNight/Rain#68]
I would like to see basic widgets of some type, since those graphic are beautiful.

**Comment by Leonavichus** [comment]
Do you have a widget on your home screen?

**Comment by Roterfux** [comment]
No. I would see this as a suggestion, or roadmap item, if you will. It's not an issue. Sorry if this might be a misunderstanding.

**Comment by Leonavichus** [comment]
No, it's just that if you mean the widget on the home screen, then this is already present #1

**Comment by Roterfux** [comment]
Hm. I don't have that available
Nova launcher

**Comment by Leonavichus** [comment]
I mean, I have it planned.

**Comment by Roterfux** [comment]
I'm an idiot. Sorry. 😂
