### ISSUE TITLE
Location does not work

### ISSUE THREAD

**Issue by d0k3** [DarkMooNight/Rain#69]
What the title says. I enable location in settings, expecting to see the current location's weather in the main screen (leftmost tab). The main screen stays completely blank for me. Setting locations manually works, though.

**Comment by Leonavichus** [comment]
Do you have Google services on your phone?

**Comment by d0k3** [comment]
Yes, there is a standard GApps installation on the phone. I also tried with my tablet (MicroG and open source location services, older Android version), and there are actually no problems there, location works.

**Comment by Martinligabue** [comment]
Same issue with Android 12 and microG, other apps do not have problems, this one seems to request access for a second or two, then from the notification bar the "Location in use" indicator disappears, and reappears for other two seconds after a while, and so on

**Comment by Leonavichus** [comment]
I will try to fix it by the next update.

**Comment by deraffe** [comment]
Looks like there is some return value that should be checked if it's null.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      ItemScrollController.scrollTo (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:254)
#1      LocationController.readCache.<anonymous closure> (package:rain/app/controller/controller.dart:210)
#2      new Future.delayed.<anonymous closure> (dart:async/future.dart:427)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
```

**Comment by Leonavichus** [comment]
This error does not affect the location search in any way.

**Comment by Leonavichus** [comment]
Can you see if everything works fine in this [version](https://github.com/DarkMooNight/Rain/releases/tag/v.3.5-beta)?

**Comment by d0k3** [comment]
Tried the ARM8 / FOSS version and location works as it should. Do you want me to try the GMS version, too? Otherwise this one can be closed from my side. Thanks a lot, this version seems to be improved in other aspects, too. I like it a lot!

**Comment by Leonavichus** [comment]
You don't have to try the gms version. Thanks for checking.

**Comment by Martinligabue** [comment]
I tried the FOSS version too, and for me it still searches for the location for a second, then gives up and loads indefinitely. Does it matter if it's the release or just the armv8?

**Comment by Leonavichus** [comment]
> I tried the FOSS version too, and for me it still searches for the location for a second, then gives up and loads indefinitely. Does it matter if it's the release or just the armv8?

To be honest, I do not know, I am fixing the location search error blindly, since in previous versions I did not have any problems with this.

**Comment by Leonavichus** [comment]
#97
