### ISSUE TITLE
 Добавить провайдера MET Norway

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#73]
Он тоже с открытым кодом (вроде)

Сегодня я понял что провайдер, которого использует твоё приложение неточен. Очень неточен. Однако MET Norway более точен. Я бы хотел иметь выбор. В Prognoza можно выбрать между этими двумя.

это приложение сделало это:
https://github.com/davidtakac/prognoza
https://apt.izzysoft.de/fdroid/index/apk/hr.dtakac.prognoza

Твоё приложение гораздо более удобное чем Prognoza. Я бы не хотел переходить на более плохое приложение ..

**Comment by Leonavichus** [comment]
Хорошо, я посмотрю. Но после того как я сдам диплом. Где-то в конце июня будет крупная обнова.

**Comment by Leonavichus** [comment]
Я посмотрел, там данных можно вывести меньше, нежели в Open Meteo. Да и там в основном все сделано для северных стран Европы.
