### ISSUE TITLE
Text is truncated

### ISSUE THREAD

**Issue by xfarrow** [DarkMooNight/Rain#82]
![IMG_20230717_235643](https://github.com/DarkMooNight/Rain/assets/49845537/0df6b328-dade-473c-9b9d-c3eb62c125ac)
In the image I provided, there's written "temperatura app..." and I was unable to read what it meant, even by clicking on it. Can it be fixed? Thank you.

P.S. Looking in the code, it is "temperatura apparente minima" and "temperatura apparente massima" but I think they don't make much sense in Italian. What did you mean to say? Something else maybe?

**Comment by xfarrow** [comment]
Edit: okay I've found its meaning. In Italian it should be "Temperatura massima percepita" (hottest) "Temperatura minima percepita" (coldest)

**Comment by Leonavichus** [comment]
Thanks for the correction, I'll fix it.

**Comment by xfarrow** [comment]
Thank you very much!
