### ISSUE TITLE
[feature request] add allergies day forecast

### ISSUE THREAD

**Issue by Emma0Z** [DarkMooNight/Rain#85]
Hi there! 

Is there any possibility to add allergies forecast into the weather forecast screen?

Here is an example: https://www.accuweather.com/en/en/saumur/135998/allergies-weather/135998

You also have an integration example with "Geometric Weather" https://github.com/WangDaYeeeeee/GeometricWeather

Thanks :)

**Comment by Leonavichus** [comment]
Hi, I'll see what I can do when I finish more meaningful improvements. And there is already such an issue #64/

**Comment by Emma0Z** [comment]
Oh my bad, got it! 

I wasn't able to translate cyrillic over GitHub mobile 😬
