### ISSUE TITLE
Автоматический поиск местоположение не работает после изменений 

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#86]
Android 12, miui 13.0.5, 1.2.2

**Comment by Leonavichus** [comment]
Я без понятия как это исправлять, так как у меня ошибка не воспроизводится и все работает нормально.

**Comment by Leonavichus** [comment]
я все равно не знаю как это исправлять, мне нужен телефон на котором такая же ошибка, чтобы посмотреть что не так
