### ISSUE TITLE
Возможность вставлять координаты как раньше

### ISSUE THREAD

**Issue by Wjxfi** [DarkMooNight/Rain#87]
Вручную вводить слишком долго
![822ddf62-c861-42c9-8af4-147b2823a2e2.jpg](https://github.com/DarkMooNight/Rain/assets/113500363/2c74703c-91b7-4d2f-b0ad-fa73d0652f45)

**Comment by Leonavichus** [comment]
![Screenshot_2023-07-24-22-46-38-41_978e420477404017796905b3c9af0ff9.jpg](https://github.com/DarkMooNight/Rain/assets/70684753/c471c4c9-58af-44c6-b4b2-6274e236bb00)

У меня все работает, задал и появилась кнопка вставки

**Comment by Leonavichus** [comment]
у меня так же, если в буфере обмена ничего нет
