### ISSUE TITLE
offline work

### ISSUE THREAD

**Issue by rsssxd** [DarkMooNight/Rain#88]
The application will not work without an internet connection. This offline application does not offer a useful way to look at its data.

**Comment by Leonavichus** [comment]
It works without internet

**Comment by rsssxd** [comment]
https://github.com/DarkMooNight/Rain/assets/60405617/de767d15-1c90-400f-8fd5-5bf5759b2195

**Comment by Leonavichus** [comment]
https://github.com/DarkMooNight/Rain/assets/70684753/707135ca-df28-4a83-8b5c-af7bcf6462aa

**Comment by rsssxd** [comment]
https://github.com/DarkMooNight/Rain/assets/60405617/4cddddf5-ab1c-451f-8a8c-e4a4c717b4ee

Unfortunately it's not working properly for me.

**Comment by Leonavichus** [comment]
The problem is that I don't even know why it doesn't work for you

**Comment by rsssxd** [comment]
It works when I refresh without internet.

https://github.com/DarkMooNight/Rain/assets/60405617/911ca47a-297b-4003-a2fa-56db53b4f7bc

**Comment by Leonavichus** [comment]
this is strange

**Comment by rsssxd** [comment]
Everything works without problems.
