### ISSUE TITLE
Temperature conversion issue

### ISSUE THREAD

**Issue by HairyMilkshakes** [DarkMooNight/Rain#92]
Hi, the temperature conversion from C to F seems to be incorrect. Please see pic below.

Right now it's about 70F and the displayed temperature is definitely incorrect.
![Screenshot_20230727_223145](https://github.com/DarkMooNight/Rain/assets/13473043/db51a6fe-d40c-4700-bd9c-9c4ee18257d5)

**Comment by Leonavichus** [comment]
#61

**Comment by Leonavichus** [comment]
Look at what is written there, then the solution to your problem

**Comment by HairyMilkshakes** [comment]
Thanks for the info, closed.
