### ISSUE TITLE
No internet connection 

### ISSUE THREAD

**Issue by AanooBeta** [DarkMooNight/Rain#94]
I am using internet and it's working I have tried on two devices it showed the same issue no internet connection why
![Screenshot_20230801-150259](https://github.com/DarkMooNight/Rain/assets/108539997/97c40ea9-3158-4e38-a817-9d1c96ec16ad)

**Comment by Leonavichus** [comment]
I honestly don't know, so far you are the second person with such an error, I tried to reproduce this error on some of my devices, but nothing came out.

**Comment by Leonavichus** [comment]
I will be rewriting the Internet connection verification code in the near future, it may be possible to fix this error.

**Comment by AanooBeta** [comment]
Oh okay maybe it's like country issue I'm from Pakistan

**Comment by Leonavichus** [comment]
Can you try this [version](https://github.com/DarkMooNight/Rain/releases/tag/v.3.4-beta)?

**Comment by AanooBeta** [comment]
Yes, of course but sadly in Pakistan where I'm from yt music arrived after
you guys launched 🤓😹

**Comment by AanooBeta** [comment]
Sorry I replied to wrong email and it's working perfectly fineee
