### ISSUE TITLE
No internet connection while driving

### ISSUE THREAD

**Issue by trueberryless** [DarkMooNight/Rain#96]
I think that there might be a bug when driving or on any other transport method with the internet connection.

Every time I was in a car, it didn't have internet access, as you can see in the screenshot.

Overall, moving with fast speed could be the problem...

But maybe I'm wrong...

![Screenshot_20230811-125101_Rain.png](https://github.com/DarkMooNight/Rain/assets/99918022/a8590e77-a7f6-4868-a087-5ddc7663e755)

It definitely had nothing to do with my internet connection. Otherwise this issue wouldn't exist yet...

**Comment by trueberryless** [comment]
Maybe this is why #94 didn't work as well...

**Comment by Leonavichus** [comment]
Can you try this [version](https://github.com/DarkMooNight/Rain/releases/tag/v.3.4-beta)?

**Comment by trueberryless** [comment]
Ok, finally being able to test it again...

It seems to work perfectly now while driving. I don't get the internet connection error any more. Thank you!

Btw: Beautiful app design! I really love it...
